from pydantic import BaseModel, Field


class PasswordResponseModel(BaseModel):
    score: int = Field(
        ...,
        ge=0,
        le=4,
        description="The strength score of the password from 0 (very weak) to 4 (very strong)."
    )
    label: str = Field(
        ...,
        description="A user-friendly readable label describing the password strength."
    )
    color: str = Field(
        ...,
        description="The hex color code matching the password strength level for UI rendering."
    )
    description: str = Field(
        ...,
        description="Detailed compliance feedback or audit details regarding HIPAA/FedRAMP requirements."
    )
    is_compliant: bool = Field(
        ...,
        description="Flag indicating if the password meets the minimum required compliance threshold (score >= 3)."
    )
    suggestions: list[str] = Field(
        default=[],
        description="Actionable improvement suggestions generated by the validator or zxcvbn."
    )

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "score": 4,
                    "label": "Very strong",
                    "color": "#2E7D32",
                    "description": "Recommended password strength by HIPAA/FedRAMP.",
                    "is_compliant": True,
                    "suggestions": []
                }
            ]
        }
    }
